"""Initial migration.

Revision ID: cde4e96d14af
Revises: fc66527e668e
Create Date: 2021-11-13 18:38:31.069415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde4e96d14af'
down_revision = 'fc66527e668e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.add_column('uf', sa.Column('sigla', sa.String(length=2), nullable=False))
    op.create_unique_constraint(None, 'uf', ['sigla'])
    op.add_column('users', sa.Column('usuario', sa.String(length=200), nullable=False))
    op.add_column('users', sa.Column('id_pessoa', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=False))
    op.add_column('users', sa.Column('delete_', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['usuario'])
    op.drop_column('users', 'nome')
    op.drop_column('users', 'id_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_email', sa.INTEGER(), nullable=False))
    op.add_column('users', sa.Column('nome', sa.VARCHAR(length=200), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'delete_')
    op.drop_column('users', 'email')
    op.drop_column('users', 'id_pessoa')
    op.drop_column('users', 'usuario')
    op.drop_constraint(None, 'uf', type_='unique')
    op.drop_column('uf', 'sigla')
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('author', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date_posted', sa.DATETIME(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
