"""Initial migration.

Revision ID: fc66527e668e
Revises: 
Create Date: 2021-10-16 18:37:57.183209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc66527e668e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ano_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.String(length=4), nullable=False),
    sa.Column('delete_', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dimensoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('delete_', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('delete_', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('id_uf', sa.Integer(), nullable=False),
    sa.Column('delete_', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=50), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_social', sa.String(length=255), nullable=False),
    sa.Column('id_email', sa.Integer(), nullable=False),
    sa.Column('id_tipo_pessoa', sa.Integer(), nullable=False),
    sa.Column('id_uf', sa.Integer(), nullable=False),
    sa.Column('delete_', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regiao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('delete_', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.String(length=255), nullable=False),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('id_ano_base', sa.Integer(), nullable=False),
    sa.Column('id_instituicao', sa.Integer(), nullable=False),
    sa.Column('id_respondido_por', sa.Integer(), nullable=False),
    sa.Column('id_variavel', sa.Integer(), nullable=False),
    sa.Column('delete_', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_indicadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('id_dimensao', sa.Integer(), nullable=False),
    sa.Column('delete_', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Integer(), nullable=False),
    sa.Column('delete_', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('id_regiao', sa.Integer(), nullable=False),
    sa.Column('delete_', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('id_email', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_email')
    )
    op.create_table('variavel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('id_dimensao', sa.Integer(), nullable=False),
    sa.Column('delete_', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variavel')
    op.drop_table('users')
    op.drop_table('uf')
    op.drop_table('tipo_pessoa')
    op.drop_table('sub_indicadores')
    op.drop_table('respostas')
    op.drop_table('regiao')
    op.drop_table('post')
    op.drop_table('pessoa')
    op.drop_table('municipio')
    op.drop_table('email')
    op.drop_table('dimensoes')
    op.drop_table('ano_base')
    # ### end Alembic commands ###
